TYPE=VIEW
query=select 0 AS `CODE`,\'Cumulé\' AS `LIB_CUMUL` union all select 1 AS `1`,\'Non cumulé\' AS `Non cumulé` order by `CODE`
md5=b34629a157adb3ab1879f1be17e662a4
updatable=0
algorithm=0
definer_user=darties1
definer_host=localhost
suid=2
with_check_option=0
timestamp=2016-10-07 09:42:46
create-version=1
source=SELECT 0 AS CODE,\'Cumulé\' AS LIB_CUMUL\nUNION ALL\nSELECT 1,\'Non cumulé\' ORDER BY 1
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select 0 AS `CODE`,\'Cumul├®\' AS `LIB_CUMUL` union all select 1 AS `1`,\'Non cumul├®\' AS `Non cumul├®` order by `CODE`
