TYPE=VIEW
query=select 0 AS `CODE`,\'Toutes les enseignes\' AS `LIB_ENSEIGNE` union all select `darties1`.`dim_enseigne`.`ID_ENSEIGNE` AS `ID_ENSEIGNE`,`darties1`.`dim_enseigne`.`LIB_ENSEIGNE` AS `LIB_ENSEIGNE` from `darties1`.`dim_enseigne` order by `CODE`
md5=cb534edce4d26c6a28a78127a270118e
updatable=0
algorithm=0
definer_user=darties1
definer_host=localhost
suid=2
with_check_option=0
timestamp=2016-10-07 09:42:46
create-version=1
source=SELECT 0 AS CODE,\'Toutes les enseignes\' AS LIB_ENSEIGNE \nUNION ALL\nSELECT dim_enseigne.ID_ENSEIGNE,dim_enseigne.LIB_ENSEIGNE FROM dim_enseigne\nORDER BY 1
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select 0 AS `CODE`,\'Toutes les enseignes\' AS `LIB_ENSEIGNE` union all select `darties1`.`dim_enseigne`.`ID_ENSEIGNE` AS `ID_ENSEIGNE`,`darties1`.`dim_enseigne`.`LIB_ENSEIGNE` AS `LIB_ENSEIGNE` from `darties1`.`dim_enseigne` order by `CODE`
