TYPE=VIEW
query=select `darties1`.`devise`.`ID_DEVISE` AS `CODE`,`darties1`.`devise`.`LIB_DEVISE` AS `LIB_devise` from `darties1`.`devise` order by `darties1`.`devise`.`ID_DEVISE`
md5=3f5404570317cdd2c6de7efecca8009a
updatable=1
algorithm=0
definer_user=darties1
definer_host=localhost
suid=2
with_check_option=0
timestamp=2016-10-07 09:42:46
create-version=1
source=SELECT ID_devise,LIB_devise from devise ORDER BY 1
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `darties1`.`devise`.`ID_DEVISE` AS `CODE`,`darties1`.`devise`.`LIB_DEVISE` AS `LIB_devise` from `darties1`.`devise` order by `darties1`.`devise`.`ID_DEVISE`
