TYPE=VIEW
query=select 0 AS `CODE`,\'Toute la france\' AS `LIBELLE` union all select (`darties1`.`dim_geographique_com`.`ID_REGION_COM` * 100) AS `CODE`,`darties1`.`dim_geographique_com`.`LIB_REGION_COM` AS `LIBELLE` from `darties1`.`dim_geographique_com` union all select ((`darties1`.`dim_departement`.`ID_REGION_COM` * 100) + `darties1`.`dim_magasin`.`ID_MAGASIN`) AS `CODE`,`darties1`.`dim_magasin`.`VILLE` AS `LIBELLE` from `darties1`.`dim_geographique_com` join `darties1`.`dim_magasin` join `darties1`.`dim_departement` where ((`darties1`.`dim_magasin`.`DEP` = `darties1`.`dim_departement`.`ID_DEPARTEMENT`) and (`darties1`.`dim_geographique_com`.`ID_REGION_COM` = `darties1`.`dim_departement`.`ID_REGION_COM`)) union all select ((`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` + 9) * 100) AS `CODE`,`darties1`.`dim_geographique_admin`.`LIB_REGION_ADMIN` AS `LIBELLE` from `darties1`.`dim_geographique_admin` where (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` < 23) union all select (((`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` + 9) * 100) + `darties1`.`dim_magasin`.`ID_MAGASIN`) AS `CODE`,`darties1`.`dim_magasin`.`VILLE` AS `LIBELLE` from `darties1`.`dim_geographique_admin` join `darties1`.`dim_departement` join `darties1`.`dim_magasin` where ((`darties1`.`dim_magasin`.`DEP` = `darties1`.`dim_departement`.`ID_DEPARTEMENT`) and (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` = `darties1`.`dim_departement`.`ID_REGION_ADMIN1`) and (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` < 23)) union all select ((`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` + 9) * 100) AS `CODE`,`darties1`.`dim_geographique_admin`.`LIB_REGION_ADMIN` AS `LIBELLE` from `darties1`.`dim_geographique_admin` where (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` >= 23) union all select (((`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` + 9) * 100) + `darties1`.`dim_magasin`.`ID_MAGASIN`) AS `CODE`,`darties1`.`dim_magasin`.`VILLE` AS `LIBELLE` from `darties1`.`dim_geographique_admin` join `darties1`.`dim_departement` join `darties1`.`dim_magasin` where ((`darties1`.`dim_magasin`.`DEP` = `darties1`.`dim_departement`.`ID_DEPARTEMENT`) and (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` = `darties1`.`dim_departement`.`ID_REGION_ADMIN2`) and (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` >= 23)) order by `CODE`
md5=75070f88976a9ea7f606a67b91850466
updatable=0
algorithm=0
definer_user=darties1
definer_host=localhost
suid=2
with_check_option=0
timestamp=2016-10-07 09:42:47
create-version=1
source=SELECT 0 as CODE,\'Toute la france\' AS LIBELLE UNION ALL\nSELECT dim_geographique_com.ID_REGION_COM*100 as CODE,LIB_REGION_COM as LIBELLE\nFROM dim_geographique_com\nUNION ALL\nSELECT dim_departement.ID_REGION_COM*100+ID_MAGASIN as CODE, VILLE as LIBELLE\nFROM dim_geographique_com,dim_magasin, dim_departement\nWHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_com.ID_REGION_COM=dim_departement.ID_REGION_COM\nUNION ALL\nSELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100 as CODE,LIB_REGION_ADMIN as LIBELLE\nFROM dim_geographique_admin\nWHERE ID_REGION_ADMIN<23\nUNION ALL\nSELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100+ID_MAGASIN as CODE, VILLE as LIBELLE\nFROM dim_geographique_admin,dim_departement,dim_magasin\nWHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_admin.ID_REGION_ADMIN=dim_departement.ID_REGION_ADMIN1\nAND dim_geographique_admin.ID_REGION_ADMIN<23\nUNION ALL\nSELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100 as CODE,LIB_REGION_ADMIN as LIBELLE\nFROM dim_geographique_admin\nWHERE ID_REGION_ADMIN>=23\nUNION ALL\nSELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100+ID_MAGASIN as CODE, VILLE as LIBELLE\nFROM dim_geographique_admin,dim_departement,dim_magasin\nWHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_admin.ID_REGION_ADMIN=dim_departement.ID_REGION_ADMIN2\nAND dim_geographique_admin.ID_REGION_ADMIN>=23\nORDER BY CODE
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select 0 AS `CODE`,\'Toute la france\' AS `LIBELLE` union all select (`darties1`.`dim_geographique_com`.`ID_REGION_COM` * 100) AS `CODE`,`darties1`.`dim_geographique_com`.`LIB_REGION_COM` AS `LIBELLE` from `darties1`.`dim_geographique_com` union all select ((`darties1`.`dim_departement`.`ID_REGION_COM` * 100) + `darties1`.`dim_magasin`.`ID_MAGASIN`) AS `CODE`,`darties1`.`dim_magasin`.`VILLE` AS `LIBELLE` from `darties1`.`dim_geographique_com` join `darties1`.`dim_magasin` join `darties1`.`dim_departement` where ((`darties1`.`dim_magasin`.`DEP` = `darties1`.`dim_departement`.`ID_DEPARTEMENT`) and (`darties1`.`dim_geographique_com`.`ID_REGION_COM` = `darties1`.`dim_departement`.`ID_REGION_COM`)) union all select ((`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` + 9) * 100) AS `CODE`,`darties1`.`dim_geographique_admin`.`LIB_REGION_ADMIN` AS `LIBELLE` from `darties1`.`dim_geographique_admin` where (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` < 23) union all select (((`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` + 9) * 100) + `darties1`.`dim_magasin`.`ID_MAGASIN`) AS `CODE`,`darties1`.`dim_magasin`.`VILLE` AS `LIBELLE` from `darties1`.`dim_geographique_admin` join `darties1`.`dim_departement` join `darties1`.`dim_magasin` where ((`darties1`.`dim_magasin`.`DEP` = `darties1`.`dim_departement`.`ID_DEPARTEMENT`) and (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` = `darties1`.`dim_departement`.`ID_REGION_ADMIN1`) and (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` < 23)) union all select ((`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` + 9) * 100) AS `CODE`,`darties1`.`dim_geographique_admin`.`LIB_REGION_ADMIN` AS `LIBELLE` from `darties1`.`dim_geographique_admin` where (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` >= 23) union all select (((`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` + 9) * 100) + `darties1`.`dim_magasin`.`ID_MAGASIN`) AS `CODE`,`darties1`.`dim_magasin`.`VILLE` AS `LIBELLE` from `darties1`.`dim_geographique_admin` join `darties1`.`dim_departement` join `darties1`.`dim_magasin` where ((`darties1`.`dim_magasin`.`DEP` = `darties1`.`dim_departement`.`ID_DEPARTEMENT`) and (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` = `darties1`.`dim_departement`.`ID_REGION_ADMIN2`) and (`darties1`.`dim_geographique_admin`.`ID_REGION_ADMIN` >= 23)) order by `CODE`
