TYPE=VIEW
query=select 0 AS `CODE`,\'Toutes les familles\' AS `LIB_FAMILLE` union all select `darties1`.`dim_famille_produit`.`ID_FAMILLE_PRODUIT` AS `ID_FAMILLE_PRODUIT`,`darties1`.`dim_famille_produit`.`LIB_FAMILLE_PRODUIT` AS `LIB_FAMILLE_PRODUIT` from `darties1`.`dim_famille_produit`
md5=cd5a1480b6503bfdb40b5ab222c5c076
updatable=0
algorithm=0
definer_user=darties1
definer_host=localhost
suid=2
with_check_option=0
timestamp=2016-10-07 09:42:46
create-version=1
source=SELECT 0 AS CODE,\'Toutes les familles\' AS LIB_FAMILLE\nUNION ALL\nSELECT ID_FAMILLE_PRODUIT, LIB_FAMILLE_PRODUIT FROM dim_famille_produit
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select 0 AS `CODE`,\'Toutes les familles\' AS `LIB_FAMILLE` union all select `darties1`.`dim_famille_produit`.`ID_FAMILLE_PRODUIT` AS `ID_FAMILLE_PRODUIT`,`darties1`.`dim_famille_produit`.`LIB_FAMILLE_PRODUIT` AS `LIB_FAMILLE_PRODUIT` from `darties1`.`dim_famille_produit`
